name: snapfind
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.0
  google_sign_in: ^5.4.4
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0
  image_picker: ^1.0.0
  geolocator: ^11.0.0
  google_generative_ai: ^0.4.0
  uuid: ^4.0.0
  firebase_messaging: ^14.9.4
  geocoding: ^3.0.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/splash/splash_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash_logo.png
  android: true
  ios: true
